package iwb.domain.db;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;


// Generated Feb 25, 2007 1:41:05 PM by Hibernate Tools 3.2.0.b9

/**
 * WDbFunc generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_db_func",schema="iwb")
public class W5DbFunc implements java.io.Serializable {

	private int dbFuncId;

	private String procName;
	
	private short logLevelTip;
	private short execRestrictTip; //0:kisitlama yok, 1:var
	private int moduleId;
	private int relatedTableId;
	private short includeApprovalFieldsFlag;
	private String insideActions;
	private String rhinoScriptCode;
	private List<W5DbFuncParam> _dbFuncParamList;

	
	@Column(name="log_level_tip")	
	public short getLogLevelTip() {
		return logLevelTip;
	}

	public void setLogLevelTip(short logLevelTip) {
		this.logLevelTip = logLevelTip;
	}

	public W5DbFunc() {
	}

	@Id
	@Column(name="db_func_id")
	public int getDbFuncId() {
		return this.dbFuncId;
	}

	public void setDbFuncId(int dbFuncId) {
		this.dbFuncId = dbFuncId;
	}


	@Column(name="proc_name")
	public String getProcName() {
		return this.procName;
	}

	public void setProcName(String procName) {
		this.procName = procName;
	}
	
	@Transient
	public List<W5DbFuncParam> get_dbFuncParamList() {
		return _dbFuncParamList;
	}

	public void set_dbFuncParamList(List<W5DbFuncParam> dbFuncParamList) {
		_dbFuncParamList = dbFuncParamList;
	}

	@Column(name="exec_restrict_tip")
	public short getExecRestrictTip() {
		return execRestrictTip;
	}

	public void setExecRestrictTip(short execRestrictTip) {
		this.execRestrictTip = execRestrictTip;
	}

	@Column(name="module_id")
	public int getModuleId() {
		return moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name="related_table_id")
	public int getRelatedTableId() {
		return relatedTableId;
	}

	public void setRelatedTableId(int relatedTableId) {
		this.relatedTableId = relatedTableId;
	}
	@Column(name="include_approval_fields_flag")
	public short getIncludeApprovalFieldsFlag() {
		return includeApprovalFieldsFlag;
	}

	public void setIncludeApprovalFieldsFlag(short includeApprovalFieldsFlag) {
		this.includeApprovalFieldsFlag = includeApprovalFieldsFlag;
	}
	@Column(name="inside_actions")
	public String getInsideActions() {
		return insideActions;
	}

	public void setInsideActions(String insideActions) {
		this.insideActions = insideActions;
	}

	@Column(name="rhino_script_code")
	public String getRhinoScriptCode() {
		return rhinoScriptCode;
	}

	public void setRhinoScriptCode(String rhinoScriptCode) {
		this.rhinoScriptCode = rhinoScriptCode;
	}	
	
	
}
