package iwb.domain.db;

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

import iwb.util.GenericUtil;

// Generated Jun 14, 2007 3:44:25 PM by Hibernate Tools 3.2.0.b9

/**
 * WEmail generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_email",schema="iwb_email")
public class W5Email implements java.io.Serializable, Log5Base {

	private int mailId;
	private int mailSettingId;
	private int customizationId;

	private int fromUserId;

	private String mailTo;
	private String mailCc;
	private String mailBcc;
	private String mailFrom;
	private	Timestamp mailDttm;

	private String mailSubject;

	private String mailBody;

	private short status;
	private short htmlFlag;
	
	private int tableId;
	private int tablePk;
	private List<W5FileAttachment> _fileAttachments;
	private W5ObjectMailSetting _oms;
	
	public String toInfluxDB() {
		StringBuilder s=new StringBuilder();
		s.append("email,oms_id=").append(_oms.getMailSettingId()).append(",status=").append(status).append(" user_id=").append(fromUserId)
			.append("i,table_id=").append(tableId).append("i,table_pk=").append(tablePk)
			.append("i,from=\"").append(GenericUtil.stringToJS2(mailFrom)).append("\",to=\"").append(GenericUtil.stringToJS2(mailTo))
			.append("\",cc=\"").append(GenericUtil.stringToJS2(mailCc)).append("\",bcc=\"").append(GenericUtil.stringToJS2(mailBcc))
			.append("\",subject=\"").append(GenericUtil.stringToJS2(mailSubject)).append("\",body=\"").append(GenericUtil.stringToJS2(mailBody)).append("\"");
		return s.toString();
	}
	
	public W5Email() {
	}

    @SequenceGenerator(name="sex_mail",sequenceName="iwb.seq_mail",allocationSize=1)
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="sex_mail")
	@Column(name="mail_id")
	public int getMailId() {
		return this.mailId;
	}

	public void setMailId(int mailId) {
		this.mailId = mailId;
	}

	@Column(name="from_user_id")
	public int getFromUserId() {
		return fromUserId;
	}


	public void setFromUserId(int fromUserId) {
		this.fromUserId = fromUserId;
	}

	@Column(name="mail_to")
	public String getMailTo() {
		return mailTo;
	}


	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name="mail_cc")
	public String getMailCc() {
		return mailCc;
	}


	public void setMailCc(String mailCc) {
		this.mailCc = mailCc;
	}


	@Column(name="mail_bcc")
	public String getMailBcc() {
		return mailBcc;
	}


	public void setMailBcc(String mailBcc) {
		this.mailBcc = mailBcc;
	}


	@Column(name="mail_from")
	public String getMailFrom() {
		return mailFrom;
	}


	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}


	@Column(name="mail_subject")
	public String getMailSubject() {
		return mailSubject;
	}


	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}


	@Column(name="mail_body")
	public String getMailBody() {
		return mailBody;
	}


	public void setMailBody(String mailBody) {
		this.mailBody = mailBody;
	}


	@Column(name="status")
	public short getStatus() {
		return status;
	}


	public void setStatus(short status) {
		this.status = status;
	}


	@Column(name="table_id")
	public int getTableId() {
		return tableId;
	}


	public void setTableId(int tableId) {
		this.tableId = tableId;
	}


	@Column(name="table_pk")
	public int getTablePk() {
		return tablePk;
	}


	public void setTablePk(int tablePk) {
		this.tablePk = tablePk;
	}


	@Column(name="mail_dttm")
	public Timestamp getMailDttm() {
		return mailDttm;
	}


	public void setMailDttm(Timestamp mailDttm) {
		this.mailDttm = mailDttm;
	}


	@Column(name="mail_setting_id")
	public int getMailSettingId() {
		return mailSettingId;
	}


	public void setMailSettingId(int mailSettingId) {
		this.mailSettingId = mailSettingId;
	}

	@Column(name="customization_id")
	public int getCustomizationId() {
		return customizationId;
	}


	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Transient
	public List<W5FileAttachment> get_fileAttachments() {
		return _fileAttachments;
	}

	public void set_fileAttachments(List<W5FileAttachment> fileAttachments) {
		_fileAttachments = fileAttachments;
	}

	public W5Email(String mailTo, String mailCc, String mailBcc,
			String mailSubject,String mailBody, List<W5FileAttachment> fileAttachments) {
		super();
		this.mailTo = mailTo;
		this.mailCc = mailCc;
		this.mailBcc = mailBcc;
		this.mailBody = mailBody;
		this.mailSubject = mailSubject;
		this._fileAttachments = fileAttachments;
	}

	@Column(name="html_flag")
	public short getHtmlFlag() {
		return htmlFlag;
	}

	public void setHtmlFlag(short htmlFlag) {
		this.htmlFlag = htmlFlag;
	}


	@Transient
	public W5ObjectMailSetting get_oms() {
		return _oms;
	}

	public void set_oms(W5ObjectMailSetting _oms) {
		this._oms = _oms;
	}
	
	
}
