package iwb.domain.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;


// Generated Feb 25, 2007 1:41:05 PM by Hibernate Tools 3.2.0.b9

/**
 * W5Help generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_help",schema="iwb")
public class W5Help implements java.io.Serializable {

	private int formCellId;
	private int customiztionId;
	private String locale;
	private String dsc;
	private int defaultWidth;
	private int defaultHeight;
	
	public void setFormCellId(int formCellId) {
		this.formCellId = formCellId;
	}
	
	@Id
	@Column(name="form_cell_id")
	public int getFormCellId() {
		return formCellId;
	}
	
	public void setCustomiztionId(int customiztionId) {
		this.customiztionId = customiztionId;
	}
	
	@Id
	@Column(name="customization_id")
	public int getCustomiztionId() {
		return customiztionId;
	}
	
	public void setLocale(String locale) {
		this.locale = locale;
	}
	
	@Id
	@Column(name="locale")
	public String getLocale() {
		return locale;
	}
	
	public void setDsc(String dsc) {
		this.dsc = dsc;
	}
	
	@Column(name="dsc")
	public String getDsc() {
		return dsc;
	}
	
	public void setDefaultWidth(int defaultWidth) {
		this.defaultWidth = defaultWidth;
	}
	
	@Column(name="default_width")
	public int getDefaultWidth() {
		return defaultWidth;
	}
	
	public void setDefaultHeight(int defaultHeight) {
		this.defaultHeight = defaultHeight;
	}
	
	@Column(name="default_height")
	public int getDefaultHeight() {
		return defaultHeight;
	}

}
