package iwb.domain.db;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

// Generated Feb 15, 2007 5:03:01 PM by Hibernate Tools 3.2.0.b9

/**
 * WTableParam generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_object_sms_mail_alarm",schema="iwb")
public class W5ObjectSmsMailAlarm  implements java.io.Serializable, W5Base {
	private int objectSmsMailAlarmId;
	private int objectSmsMailId;
	private int customizationId;
	private int tablePk;
	private int tableId;
	private short activeFlag;
	private short alarmLevel;
	private String dsc;
	private int assignedUserId;
	private Timestamp inactiveDttm;
	private short alarmFreqTip;
	private Date alarmDt;
	private String alarmTm;
	

	public W5ObjectSmsMailAlarm() {
	}

	public W5ObjectSmsMailAlarm(int objectSmsMailId, int customizationId,
			int tablePk, int tableId,String dsc,short alarmLevel, int assignedUserId, short alarmFreqTip, Date alarmDt,String alarmTm) {
		this.objectSmsMailId = objectSmsMailId;
		this.customizationId = customizationId;
		this.tablePk = tablePk;
		this.tableId = tableId;
		this.dsc = dsc;
		this.alarmLevel = alarmLevel;
		this.assignedUserId = assignedUserId;
		this.activeFlag = (short)1;
		this.alarmFreqTip = alarmFreqTip;
		this.alarmDt = alarmDt;
		this.alarmTm = alarmTm;
	}

	@SequenceGenerator(name="sex_object_sms_mail_alarm",sequenceName="seq_object_sms_mail_alarm",allocationSize=1)
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="sex_object_sms_mail_alarm")
	@Column(name="object_sms_mail_alarm_id")
	public int getObjectSmsMailAlarmId() {
		return objectSmsMailAlarmId;
	}

	public void setObjectSmsMailAlarmId(int objectSmsMailAlarmId) {
		this.objectSmsMailAlarmId = objectSmsMailAlarmId;
	}

	@Column(name="object_sms_mail_id")
	public int getObjectSmsMailId() {
		return objectSmsMailId;
	}

	public void setObjectSmsMailId(int objectSmsMailId) {
		this.objectSmsMailId = objectSmsMailId;
	}

	@Id
	@Column(name="customization_id")
	public int getCustomizationId() {
		return customizationId;
	}

	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Column(name="active_flag")
	public short getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(short activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name="table_pk")
	public int getTablePk() {
		return tablePk;
	}

	public void setTablePk(int tablePk) {
		this.tablePk = tablePk;
	}
	@Column(name="table_id")
	public int getTableId() {
		return tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Column(name="dsc")
	public String getDsc() {
		return dsc;
	}

	public void setDsc(String dsc) {
		this.dsc = dsc;
	}

	@Column(name="alarm_level")
	public short getAlarmLevel() {
		return alarmLevel;
	}

	public void setAlarmLevel(short alarmLevel) {
		this.alarmLevel = alarmLevel;
	}

	@Column(name="assigned_user_id")
	public int getAssignedUserId() {
		return assignedUserId;
	}

	public void setAssignedUserId(int assignedUserId) {
		this.assignedUserId = assignedUserId;
	}



	@Column(name="inactive_dttm")
	public Timestamp getInactiveDttm() {
		return inactiveDttm;
	}

	public void setInactiveDttm(Timestamp inactiveDttm) {
		this.inactiveDttm = inactiveDttm;
	}

	@Column(name="alarm_freq_tip")
	public short getAlarmFreqTip() {
		return alarmFreqTip;
	}

	public void setAlarmFreqTip(short alarmFreqTip) {
		this.alarmFreqTip = alarmFreqTip;
	}

	@Column(name="alarm_dt")
	public Date getAlarmDt() {
		return alarmDt;
	}

	public void setAlarmDt(Date alarmDt) {
		this.alarmDt = alarmDt;
	}

	@Column(name="alarm_tm")
	public String getAlarmTm() {
		return alarmTm;
	}

	public void setAlarmTm(String alarmTm) {
		this.alarmTm = alarmTm;
	}
	
	@Transient
	public boolean safeEquals(W5Base q){
		if(q==null)return false;
		W5ObjectSmsMailAlarm l =(W5ObjectSmsMailAlarm)q ;
		return false;
	}
	
}
