package iwb.domain.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

import iwb.util.GenericUtil;

// Generated Feb 15, 2007 2:10:19 PM by Hibernate Tools 3.2.0.b9

/**
 * WTable generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_table_user_tip",schema="iwb")
public class W5TableUserTip implements java.io.Serializable, W5Base {

	private int tableUserTipId;
	private int tableId;
	private int customizationId;
	private int userTip;

	private String accessViewSql;
	private String accessInsertSql;
	private String accessUpdateSql;
	private String accessDeleteSql;
	
	private short accessViewTip;
	private String accessViewRoles;
	private String accessViewUsers;
	private String accessViewUserFields;
	
	private short accessInsertTip; //0:kisitlama yok, 1:var
	private String accessInsertRoles;
	private String accessInsertUsers;
	
	private short accessUpdateTip;
	private String accessUpdateRoles;
	private String accessUpdateUsers;
	private String accessUpdateUserFields;
	
	private short accessDeleteTip;
	private String accessDeleteRoles;
	private String accessDeleteUsers;
	private String accessDeleteUserFields;

	private short accessPermissionTip;
	private String accessPermissionRoles;
	private String accessPermissionUsers;
	private String accessPermissionUserFields;
	
	public W5TableUserTip() {
	}


	@Column(name="table_id")
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}
	@Id
	@Column(name="table_user_tip_id")
	public int getTableUserTipId() {
		return tableUserTipId;
	}

	public void setTableUserTipId(int tableUserTipId) {
		this.tableUserTipId = tableUserTipId;
	}
	@Id
	@Column(name="customization_id")
	public int getCustomizationId() {
		return customizationId;
	}

	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Column(name="user_tip")
	public int getUserTip() {
		return userTip;
	}

	public void setUserTip(int userTip) {
		this.userTip = userTip;
	}

	@Column(name="access_view_sql")
	public String getAccessViewSql() {
		return accessViewSql;
	}

	public void setAccessViewSql(String accessViewSql) {
		this.accessViewSql = accessViewSql;
	}

	@Column(name="access_insert_sql")
	public String getAccessInsertSql() {
		return accessInsertSql;
	}

	public void setAccessInsertSql(String accessInsertSql) {
		this.accessInsertSql = accessInsertSql;
	}
	
	@Column(name="access_update_sql")
	public String getAccessUpdateSql() {
		return accessUpdateSql;
	}

	public void setAccessUpdateSql(String accessUpdateSql) {
		this.accessUpdateSql = accessUpdateSql;
	}

	@Column(name="access_delete_sql")
	public String getAccessDeleteSql() {
		return accessDeleteSql;
	}

	public void setAccessDeleteSql(String accessDeleteSql) {
		this.accessDeleteSql = accessDeleteSql;
	}

	@Column(name="access_view_tip")
	public short getAccessViewTip() {
		return accessViewTip;
	}

	@Column(name="access_view_roles")
	public String getAccessViewRoles() {
		return accessViewRoles;
	}

	@Column(name="access_view_users")
	public String getAccessViewUsers() {
		return accessViewUsers;
	}

	public void setAccessViewTip(short accessViewTip) {
		this.accessViewTip = accessViewTip;
	}

	public void setAccessViewRoles(String accessViewRoles) {
		this.accessViewRoles = accessViewRoles;
    }
	
	public void setAccessViewUsers(String accessViewUsers) {
		this.accessViewUsers = accessViewUsers;
	}
	
	@Column(name="access_insert_tip")
	public short getAccessInsertTip() {
		return accessInsertTip;
	}
	public void setAccessInsertTip(short accessInsertTip) {
		this.accessInsertTip = accessInsertTip;
	}
	@Column(name="access_insert_roles")
	public String getAccessInsertRoles() {
		return accessInsertRoles;
	}
	public void setAccessInsertRoles(String accessInsertRoles) {
		this.accessInsertRoles = accessInsertRoles;
	}
	@Column(name="access_insert_users")
	public String getAccessInsertUsers() {
		return accessInsertUsers;
	}
	public void setAccessInsertUsers(String accessInsertUsers) {
		this.accessInsertUsers = accessInsertUsers;
	}
	@Column(name="access_update_tip")
	public short getAccessUpdateTip() {
		return accessUpdateTip;
	}
	public void setAccessUpdateTip(short accessUpdateTip) {
		this.accessUpdateTip = accessUpdateTip;
	}
	@Column(name="access_update_roles")
	public String getAccessUpdateRoles() {
		return accessUpdateRoles;
	}
	public void setAccessUpdateRoles(String accessUpdateRoles) {
		this.accessUpdateRoles = accessUpdateRoles;
	}
	@Column(name="access_update_users")
	public String getAccessUpdateUsers() {
		return accessUpdateUsers;
	}
	public void setAccessUpdateUsers(String accessUpdateUsers) {
		this.accessUpdateUsers = accessUpdateUsers;
	}
	
	@Column(name="access_delete_tip")
	public short getAccessDeleteTip() {
		return accessDeleteTip;
	}
	public void setAccessDeleteTip(short accessDeleteTip) {
		this.accessDeleteTip = accessDeleteTip;
	}
	@Column(name="access_delete_roles")
	public String getAccessDeleteRoles() {
		return accessDeleteRoles;
	}
	public void setAccessDeleteRoles(String accessDeleteRoles) {
		this.accessDeleteRoles = accessDeleteRoles;
	}
	@Column(name="access_delete_users")
	public String getAccessDeleteUsers() {
		return accessDeleteUsers;
	}
	public void setAccessDeleteUsers(String accessDeleteUsers) {
		this.accessDeleteUsers = accessDeleteUsers;
	}


	@Column(name="access_permission_tip")
	public short getAccessPermissionTip() {
		return accessPermissionTip;
	}

	public void setAccessPermissionTip(short accessPermissionTip) {
		this.accessPermissionTip = accessPermissionTip;
	}

	@Column(name="access_permission_roles")
	public String getAccessPermissionRoles() {
		return accessPermissionRoles;
	}

	public void setAccessPermissionRoles(String accessPermissionRoles) {
		this.accessPermissionRoles = accessPermissionRoles;
	}

	@Column(name="access_permission_users")
	public String getAccessPermissionUsers() {
		return accessPermissionUsers;
	}

	public void setAccessPermissionUsers(String accessPermissionUsers) {
		this.accessPermissionUsers = accessPermissionUsers;
	}

	@Column(name="access_permission_user_fields")
	public String getAccessPermissionUserFields() {
		return accessPermissionUserFields;
	}
	public void setAccessPermissionUserFields(String accessPermissionUserFields) {
		this.accessPermissionUserFields = accessPermissionUserFields;
	}

	@Column(name="access_view_user_fields")
	public String getAccessViewUserFields() {
		return accessViewUserFields;
	}

	public void setAccessViewUserFields(String accessViewUserFields) {
		this.accessViewUserFields = accessViewUserFields;
	}

	@Column(name="access_update_user_fields")
	public String getAccessUpdateUserFields() {
		return accessUpdateUserFields;
	}

	public void setAccessUpdateUserFields(String accessUpdateUserFields) {
		this.accessUpdateUserFields = accessUpdateUserFields;
	}

	@Column(name="access_delete_user_fields")
	public String getAccessDeleteUserFields() {
		return accessDeleteUserFields;
	}

	public void setAccessDeleteUserFields(String accessDeleteUserFields) {
		this.accessDeleteUserFields = accessDeleteUserFields;
	}
	@Transient
	public boolean safeEquals(W5Base q){
		if(q==null)return false;
		W5TableUserTip t = (W5TableUserTip)q;
		return 	
			this.tableUserTipId==t.getTableUserTipId() &&
			this.tableId==t.getTableId() &&
			this.userTip==t.getUserTip() &&
	
			GenericUtil.safeEquals(this.accessViewSql,t.getAccessViewSql()) &&
			GenericUtil.safeEquals(this.accessUpdateSql,t.getAccessUpdateSql()) &&
			GenericUtil.safeEquals(this.accessDeleteSql,t.getAccessDeleteSql());
	}
	
	
}
