package iwb.domain.db;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

import iwb.util.GenericUtil;



/**
 * WTemplate generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_template",schema="iwb")
public class W5Template implements java.io.Serializable, W5Base {

	private int templateId;
	
	private int customizationId;
	
	private short templateTip;

	private String dsc;

	private int objectId;

	private short objectTip;

	private short localeMsgFlag;

	private String code;

	private List<W5TemplateObject> _templateObjectList;
	
	public W5Template() {
	}

	@Id
	@Column(name="template_id")
	public int getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	@Column(name="template_tip")
	public short getTemplateTip() {
		return this.templateTip;
	}

	public void setTemplateTip(short templateTip) {
		this.templateTip = templateTip;
	}

	@Column(name="dsc")
	public String getDsc() {
		return this.dsc;
	}

	public void setDsc(String dsc) {
		this.dsc = dsc;
	}

	@Column(name="object_id")
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Column(name="object_tip")
	public short getObjectTip() {
		return this.objectTip;
	}

	public void setObjectTip(short objectTip) {
		this.objectTip = objectTip;
	}
	@Id
	@Column(name="customization_id")
	public int getCustomizationId() {
		return customizationId;
	}

	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Column(name="code")
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Transient
	public List<W5TemplateObject> get_templateObjectList() {
		return _templateObjectList;
	}

	public void set_templateObjectList(List<W5TemplateObject> templateObjectList) {
		_templateObjectList = templateObjectList;
	}
	
	@Column(name="locale_msg_flag")
	public short getLocaleMsgFlag() {
		return localeMsgFlag;
	}

	public void setLocaleMsgFlag(short localeMsgFlag) {
		this.localeMsgFlag = localeMsgFlag;
	}


	@Transient
	public boolean safeEquals(W5Base q){
		if(q==null)return false;
		W5Template t = (W5Template)q;
		boolean b =  
			this.templateId == t.getTemplateId() &&
			this.templateTip == t.getTemplateTip() &&
			GenericUtil.safeEquals(this.dsc, t.getDsc()) &&
			this.objectId == t.getObjectId() &&
			this.objectTip == t.getObjectTip() &&
			this.localeMsgFlag == t.getLocaleMsgFlag() &&
			GenericUtil.safeEquals(this.code, t.getCode());
		
		if(!b)return false;
		if(!GenericUtil.safeEquals(this._templateObjectList, t._templateObjectList))return false;
/*		if(this._templateObjectList!=null && t.get_templateObjectList()!=null){
			if(this._templateObjectList.size()==t.get_templateObjectList().size())return false;
			for(int i=0;i<this._templateObjectList.size();i++){
				W5TemplateObject c1 = this._templateObjectList.get(i); 
				W5TemplateObject c2 = t.get_templateObjectList().get(i);
				if(!c1.equals(c2))return false;
			}			
		} else if(this._templateObjectList!=null ^ t.get_templateObjectList()!=null) return false;*/
		
		return true;
	}

}
